#!/bin/sh

alias ls='ls --color=auto --group-directories-first'
alias ll='ls -lh --color=auto --group-directories-first'
alias lal='ls -lah --color=auto --group-directories-first'
alias la='ls -a --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias e='emacsclient -c -n'
alias eeval='emacsclient -e'
alias et='emacsclient -t'

alias mvn='mvn -gs "$XDG_CONFIG_HOME/maven/settings.xml"'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
