#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# For JetBrains IDEs to work
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT="MToolkit"
wmname LG3D


udiskie -s &
picom --no-fading-openclose &
nm-applet &
redshift-gtk &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval "$(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)"
feh --no-fehbg --bg-scale "$HOME/Images/Wallpaper/wallpaper_reimu.jpg"
xss-lock -- i3lock -i "$HOME/Images/Wallpaper/wallpaper_hina.png" &

xinput set-prop 12 301 1
xinput set-prop 12 292 0.55

dwmstatus 2>&1 >/dev/null &
alacritty &
firefox &

exec dwm
