#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


udiskie -s &
picom --no-fading-openclose &
nm-applet &
redshift-gtk -l 45.750000:4.850000 & # Latitude and Longitude of Lyon
fcitx &

feh --no-fehbg --bg-scale "$HOME/Pictures/Wallpaper/gnu.png"
xss-lock -- i3lock -i "$HOME/Pictures/Wallpaper/gnu-lock.png" &

dwmstatus 2>&1 >/dev/null &
st &

exec dwm
