#!/bin/sh

# Source the xprofile
if [ -f "$XDG_CONFIG_HOME/X11/xprofile" ]
then
    . "$XDG_CONFIG_HOME/X11/xprofile"
else
    . "$HOME/.xprofile"
fi

# dwm needs libxft-bgra to display emojis correctly
while true
do
    dwm > /dev/null 2>&1
done
