#!/bin/sh

setbg &

udiskie -s &
picom --no-fading-openclose &
nm-applet &
redshift-gtk -l 45.750000:4.850000 &
fcitx &

xss-lock -- i3lock -i "$HOME/Pictures/Wallpaper/gnu-lock.png" &

dwmstatus >/dev/null 2>&1 &

